apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerset
spec:
  replicas: 1
  selector:
    matchLabels:
      name: containerset
  template:
    metadata:
      labels:
        name: containerset
    spec:
      serviceAccountName: containerset
      containers:
        - name: containerset
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - containerset
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "containerset"
