kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: containerset
subjects:
- kind: ServiceAccount
  name: containerset
roleRef:
  kind: Role
  name: containerset
  apiGroup: rbac.authorization.k8s.io
